name: ngTagsInput Site
markdown: redcarpet
highlighter: rouge 
exclude: ['node_modules','*.log']
stable_version: 3.2.0
baseurl: /ngTagsInput
github_pages_url: http://mbenford.github.io

collections:
  pages:
    output: true
    permalink: /:path:output_ext

  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title